---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-web
spec:
# 볼륨 특성
# 용량
  resources:
    requests:
      storage: 10Gi
# 스토리지 클래스
  storageClassName: manual
# 접근 모드
  accessModes:
    - ReadWriteMany