---
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: machinerunning              
          topologyKey: kubernetes.io/hostname